services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_EMAIL
        value: "jacksonpercy614@gmail.com"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "Playboy19."
      - key: N8N_HOST
        value: "n8n-agent-ji4a.onrender.com"
      - key: N8N_PORT
        value: "5678"
        - key: N8N_ENCRYPTION_KEY
        value: "Billion$_Mellyfx."
      - key: N8N_PROTOCOL
        value: "https"
      - key: TWELVEDATA_API_KEY
        value: "58c67e772fdb474c91949bf2e4fad427"
