name: godmode-trading-agent
on:
  schedule:
    # every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch: {} # manual run available

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz python-dateutil

      - name: Run trading agent
        env:
          TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          HF_API_KEY: ${{ secrets.HF_API_KEY }}          # optional (if you want Hugging Face check)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python agent.py

      - name: Commit log changes (if any)
        if: always()
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"
          git add signals.csv || true
          git commit -m "append signals log by action" || echo "no changes to commit"
          git push origin HEAD:main || echo "push failed (maybe read-only token)"
